# Generated by Django 4.1.1 on 2022-09-13 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to=settings.AUTH_USER_MODEL, verbose_name='С кем взаимодействовал')),
                ('initiator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to=settings.AUTH_USER_MODEL, verbose_name='Кто взаимодействовал')),
            ],
            options={
                'verbose_name': 'Журнал взаимодействий',
                'verbose_name_plural': 'Журнал взаимодействий',
            },
        ),
    ]
